### ISSUE TITLE
v0.2.0 roadmap

### ISSUE THREAD

**Issue by foxbunny** [foxbunny/beamkit#1]
# New features

- [ ] Functions for creating transition effects (#4)
- [ ] Functions for bootstrapping applications (#5)
- [ ] Functions for form validation (#12)
- [ ] Application architecture guide
- [ ] Build a complete implementation of an example app
- [x] ~Functions for working with keyed arrays/nodes (#21)~
- [x] ~Functions for working with XHR requests (#2)~
- [x] ~Functions for working with navigation events (#3)~

## Functions for working with navigation events

Instead of providing a typical routing implementation, define a data structure that will hold parsed location data (path segments, query parameters, hashes) and functions for converting between URL and the data structure. Also provide event emitter that fires events on programmatic navigation and popstate event.

## Functions for working with XHR

Provide an easy-to-use API for XHR requests with focus on easy error handling.

## Functions for creating transition effects

Provide functions for setting classes before and as elements are introduced to or removed from the DOM tree.

## Functions for bootstrapping applications

Provide functions that set up application state and allow navigating between modules in a standardized way.

## Application architecture guide

Document the process of building applications using the provided functionality.
